### ISSUE TITLE
Invitation - Express backend app

### ISSUE THREAD

**Issue by brunolnetto** [Shyam-Chen/Express-Starter#75]
Hi Shyam C.,

I wrote a express-based [backend app](https://github.com/trouchet/sappio), we call it a boilerplate. I was able to learn from your repository. Feel free to take a look at mine.  

Best regards,
Bruno P.

**Comment by brunolnetto** [comment]
In your opinion, what is it better than Express and KoA? A great reference of mine uses it very much.

**Comment by Shyam-Chen** [comment]
I prefer the Fastify plugin system to the Express/Koa middleware pattern. More Fastify plugins are maintained by the Fastify core team, such as `@fastify/websocket`, `@fastify/jwt`. Regarding performance, Fastify is better than Express and Koa.

```ts
// Fastify - async/await out of the box
router.post('/', { onRequest: [auth] }, async (req, reply) => {
  const result = await users.sthFn();
  return reply.send(result);
});

// Express
router.post('/', auth, async (req, res, next) => {
  try {
    const result = await users.sthFn();
    res.json(result);
  } catch (error) {
    return next(error);
  }
});
```

**Comment by brunolnetto** [comment]
I see you are able to understand the structure of a (backend) application well. Would you recommend me some (brief) material about web socket?

**Comment by Shyam-Chen** [comment]
- https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
- https://github.com/websockets/ws

Or use Server-sent events

**Comment by brunolnetto** [comment]
When we create an app from express, do we create a websocket?

**Comment by Shyam-Chen** [comment]
Depending on your business conditions.

**Comment by Shyam-Chen** [comment]
I have created `vite-plugin-fastify` and `vite-plugin-fastify-routes` to enable Fastify development with Vite in TypeScript. Below is a link to a simple template:

https://github.com/Vanilla-IceCream/vite-plugin-fastify-routes/tree/main/examples

**Comment by brunolnetto** [comment]
Great, @Shyam-Chen! I did not had experience with fastify still. I am not a web developer either, but a curious person.
